services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: signin_php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    networks:
      - signin-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  caddy:
    image: caddy:2-alpine
    container_name: signin_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      - ../public:/var/www/html/public:ro
    depends_on:
      - php
    networks:
      - signin-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local

networks:
  signin-network:
    driver: bridge

